// gallery-data.js
// Generated by scripts/generate-gallery-data.mjs from gallery-sources.json and /assets.
// Upload new photos into /assets with names that include a configured keyword.
window.GALLERY = {
  "bathroom": {
    "title": "Bathroom Remodels",
    "groups": [
      {
        "name": "Bathroom Remodels",
        "images": [
          {
            "src": "./assets/Batch2/Bath 1.jpg",
            "mtime": 1769383240012
          },
          {
            "src": "./assets/Batch2/Bath 2.jpg",
            "mtime": 1769383255531
          },
          {
            "src": "./assets/Batch2/Bath 3.jpg",
            "mtime": 1769383267958
          },
          {
            "src": "./assets/Bathroom1.jpg",
            "mtime": 1766078121630
          },
          {
            "src": "./assets/Bathroom2.jpg",
            "mtime": 1766078121647
          },
          {
            "src": "./assets/Bathroom3.jpg",
            "mtime": 1766078121636
          }
        ]
      },
      {
        "name": "Shower Remodels",
        "images": [
          {
            "src": "./assets/Batch2/Shower Remodel 2.jpg",
            "mtime": 1769383335984
          },
          {
            "src": "./assets/Batch2/Shower Remodel 3.jpg",
            "mtime": 1769383359869
          },
          {
            "src": "./assets/Batch2/Shower Remodel 4.jpg",
            "mtime": 1769383378575
          },
          {
            "src": "./assets/Batch2/Shower Remodel 5.jpg",
            "mtime": 1769383395822
          },
          {
            "src": "./assets/Batch2/Shower Remodel 6.jpg",
            "mtime": 1769383429938
          },
          {
            "src": "./assets/Batch2/Shower Remodel 7.jpg",
            "mtime": 1769383445726
          },
          {
            "src": "./assets/Batch2/Shower Remodel 8.jpg",
            "mtime": 1769383473184
          },
          {
            "src": "./assets/Batch2/Shower Remodel 9.jpg",
            "mtime": 1769383459803
          },
          {
            "src": "./assets/Batch2/Shower Remodel 10.jpg",
            "mtime": 1769383494860
          },
          {
            "src": "./assets/Shower1.jpg",
            "mtime": 1766078121683
          },
          {
            "src": "./assets/Shower2.jpg",
            "mtime": 1766078121668
          },
          {
            "src": "./assets/Shower3.jpg",
            "mtime": 1766078121663
          },
          {
            "src": "./assets/Shower4.jpg",
            "mtime": 1766078121689
          },
          {
            "src": "./assets/Shower5.jpg",
            "mtime": 1766078121642
          },
          {
            "src": "./assets/Shower6.jpg",
            "mtime": 1766078121723
          },
          {
            "src": "./assets/Shower7.jpg",
            "mtime": 1766078121657
          }
        ]
      }
    ]
  },
  "fencing": {
    "title": "Fencing",
    "groups": [
      {
        "name": "Fence Installations",
        "images": [
          {
            "src": "./assets/Fence May 2026 - 1.jpg",
            "mtime": 1778622573093
          },
          {
            "src": "./assets/Fence May 2026 - 2.jpg",
            "mtime": 1778622581057
          },
          {
            "src": "./assets/Fence May 2026 - 3.jpg",
            "mtime": 1778622575923
          },
          {
            "src": "./assets/Fence May 2026 - 4.jpg",
            "mtime": 1778622574299
          },
          {
            "src": "./assets/Fence May 2026 - 5.jpg",
            "mtime": 1778622577195
          },
          {
            "src": "./assets/Fence May 2026 - 6.jpg",
            "mtime": 1778622571317
          },
          {
            "src": "./assets/Fence May 2026 - 7.jpg",
            "mtime": 1778622578816
          },
          {
            "src": "./assets/Fence May 2026 - 8.jpg",
            "mtime": 1778622644956
          },
          {
            "src": "./assets/Fence1.jpg",
            "mtime": 1766078121756
          },
          {
            "src": "./assets/Fence2.jpg",
            "mtime": 1766078121707
          },
          {
            "src": "./assets/Fence3.jpg",
            "mtime": 1766078121677
          },
          {
            "src": "./assets/Fence4.jpg",
            "mtime": 1766078121698
          },
          {
            "src": "./assets/Fence5.jpg",
            "mtime": 1766078121734
          },
          {
            "src": "./assets/Fence6.jpg",
            "mtime": 1766078121748
          },
          {
            "src": "./assets/Fence7.jpg",
            "mtime": 1766078121741
          }
        ]
      }
    ]
  },
  "concrete": {
    "title": "Concrete Work",
    "groups": [
      {
        "name": "Concrete Work",
        "images": [
          {
            "src": "./assets/Batch2/Concrete Work 1.jpg",
            "mtime": 1769383286833
          },
          {
            "src": "./assets/Batch2/Concrete Work 2.jpg",
            "mtime": 1769383305380
          },
          {
            "src": "./assets/Batch2/Concrete Work 3.jpg",
            "mtime": 1769383318181
          }
        ]
      }
    ]
  }
};
